SEED: 7777

OPTIM:
  LR: 0.004
  WEIGHT_DECAY: 0.0001
  MAX_EPOCH: 50

DATASET:
  ROOT: data

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 512
  TEST:
    BATCH_SIZE: 512

TEST:
  FINAL_MODEL: best_val
  EVALUATOR: Classification
